crab status -d crab_DoubleEG_B
crab status -d crab_DoubleEG_C
crab status -d crab_DoubleEG_D
crab status -d crab_DoubleEG_E
crab status -d crab_DoubleEG_F
crab status -d crab_SingleEG_B
crab status -d crab_SingleEG_C
crab status -d crab_SingleEG_D
crab status -d crab_SingleEG_E
crab status -d crab_SingleEG_F
crab status -d crab_MuonEG_B
crab status -d crab_MuonEG_C
crab status -d crab_MuonEG_D
crab status -d crab_MuonEG_E
crab status -d crab_MuonEG_F
crab status -d crab_DoubleMuon_B
crab status -d crab_DoubleMuon_C
crab status -d crab_DoubleMuon_D
crab status -d crab_DoubleMuon_E
crab status -d crab_DoubleMuon_F
crab status -d crab_SingleMuon_B
crab status -d crab_SingleMuon_C
crab status -d crab_SingleMuon_D
crab status -d crab_SingleMuon_E
crab status -d crab_SingleMuon_F
crab status -d crab_MET_B
crab status -d crab_MET_C
crab status -d crab_MET_D
crab status -d crab_MET_E
crab status -d crab_MET_F
crab status -d crab_TTTo2L2Nu
crab status -d crab_DY
crab status -d crab_WJets
crab status -d crab_TTTo1L
crab status -d crab_WW
crab status -d crab_WWW_1
crab status -d crab_WWW_2
crab status -d crab_WWZ_1
crab status -d crab_WWZ_2
crab status -d crab_WZ
crab status -d crab_WZZ
crab status -d crab_ZZ
crab status -d crab_ZZZ_1
crab status -d crab_ZZZ_2
crab status -d crab_tW
crab status -d crab_t_sch
crab status -d crab_t_tch
crab status -d crab_tbarW
crab status -d crab_tbar_tch
crab status -d crab_tZq
crab status -d crab_ttH
crab status -d crab_ttWLNu
crab status -d crab_ttWW
crab status -d crab_ttWZ
crab status -d crab_ttWtoQQ
crab status -d crab_ttZ
crab status -d crab_ttZZ
#crab status -d crab_ttZtoNuNu
crab status -d crab_ttZtoQQ
crab status -d crab_QCD_50to80
crab status -d crab_QCD_80to120
crab status -d crab_QCD_120to170
crab status -d crab_QCD_170to300
crab status -d crab_QCD_300toinf
