crab resubmit -d crab_DoubleEG_B
crab resubmit -d crab_DoubleEG_C
crab resubmit -d crab_DoubleEG_D
crab resubmit -d crab_DoubleEG_E
crab resubmit -d crab_DoubleEG_F
crab resubmit -d crab_SingleEG_B
crab resubmit -d crab_SingleEG_C
crab resubmit -d crab_SingleEG_D
crab resubmit -d crab_SingleEG_E
crab resubmit -d crab_SingleEG_F
crab resubmit -d crab_MuonEG_B
crab resubmit -d crab_MuonEG_C
crab resubmit -d crab_MuonEG_D
crab resubmit -d crab_MuonEG_E
crab resubmit -d crab_MuonEG_F
crab resubmit -d crab_DoubleMuon_B
crab resubmit -d crab_DoubleMuon_C
crab resubmit -d crab_DoubleMuon_D
crab resubmit -d crab_DoubleMuon_E
crab resubmit -d crab_DoubleMuon_F
crab resubmit -d crab_SingleMuon_B
crab resubmit -d crab_SingleMuon_C
crab resubmit -d crab_SingleMuon_D
crab resubmit -d crab_SingleMuon_E
crab resubmit -d crab_SingleMuon_F
crab resubmit -d crab_MET_B
crab resubmit -d crab_MET_C
crab resubmit -d crab_MET_D
crab resubmit -d crab_MET_E
crab resubmit -d crab_MET_F
crab resubmit -d crab_TTTo2L2Nu
crab status -d crab_DY
